packages:
  - "."

allowBuilds:
  esbuild: true
  puppeteer: true

verifyDepsBeforeRun: false

overrides:
  "@types/express": "5.0.6"
  "@types/express-serve-static-core": "5.1.1"
  "@types/node": "25.5.0"